@if($rating == 0)
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 0.5)
    <i class="fas fa-star-half-alt fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 1)
    <i class="fas fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 1.5)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star-half-alt fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 2)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 2.5)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star-half-alt fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 3)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 3.5)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star-half-alt fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 4)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="far fa-star fa-lg"></i>
@elseif($rating <= 4.5)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star-half-alt fa-lg"></i>
@elseif($rating <= 5)
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
    <i class="fas fa-star fa-lg"></i>
@endif
({{$count}})